require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BetaAccessRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # BetaAccessRequest. As you add validations to BetaAccessRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "email" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BetaAccessRequestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all beta_access_requests as @beta_access_requests" do
      beta_access_request = BetaAccessRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:beta_access_requests).should eq([beta_access_request])
    end
  end

  describe "GET show" do
    it "assigns the requested beta_access_request as @beta_access_request" do
      beta_access_request = BetaAccessRequest.create! valid_attributes
      get :show, {:id => beta_access_request.to_param}, valid_session
      assigns(:beta_access_request).should eq(beta_access_request)
    end
  end

  describe "GET new" do
    it "assigns a new beta_access_request as @beta_access_request" do
      get :new, {}, valid_session
      assigns(:beta_access_request).should be_a_new(BetaAccessRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested beta_access_request as @beta_access_request" do
      beta_access_request = BetaAccessRequest.create! valid_attributes
      get :edit, {:id => beta_access_request.to_param}, valid_session
      assigns(:beta_access_request).should eq(beta_access_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BetaAccessRequest" do
        expect {
          post :create, {:beta_access_request => valid_attributes}, valid_session
        }.to change(BetaAccessRequest, :count).by(1)
      end

      it "assigns a newly created beta_access_request as @beta_access_request" do
        post :create, {:beta_access_request => valid_attributes}, valid_session
        assigns(:beta_access_request).should be_a(BetaAccessRequest)
        assigns(:beta_access_request).should be_persisted
      end

      it "redirects to the created beta_access_request" do
        post :create, {:beta_access_request => valid_attributes}, valid_session
        response.should redirect_to(BetaAccessRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved beta_access_request as @beta_access_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        BetaAccessRequest.any_instance.stub(:save).and_return(false)
        post :create, {:beta_access_request => { "email" => "invalid value" }}, valid_session
        assigns(:beta_access_request).should be_a_new(BetaAccessRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BetaAccessRequest.any_instance.stub(:save).and_return(false)
        post :create, {:beta_access_request => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested beta_access_request" do
        beta_access_request = BetaAccessRequest.create! valid_attributes
        # Assuming there are no other beta_access_requests in the database, this
        # specifies that the BetaAccessRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BetaAccessRequest.any_instance.should_receive(:update_attributes).with({ "email" => "MyString" })
        put :update, {:id => beta_access_request.to_param, :beta_access_request => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested beta_access_request as @beta_access_request" do
        beta_access_request = BetaAccessRequest.create! valid_attributes
        put :update, {:id => beta_access_request.to_param, :beta_access_request => valid_attributes}, valid_session
        assigns(:beta_access_request).should eq(beta_access_request)
      end

      it "redirects to the beta_access_request" do
        beta_access_request = BetaAccessRequest.create! valid_attributes
        put :update, {:id => beta_access_request.to_param, :beta_access_request => valid_attributes}, valid_session
        response.should redirect_to(beta_access_request)
      end
    end

    describe "with invalid params" do
      it "assigns the beta_access_request as @beta_access_request" do
        beta_access_request = BetaAccessRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BetaAccessRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => beta_access_request.to_param, :beta_access_request => { "email" => "invalid value" }}, valid_session
        assigns(:beta_access_request).should eq(beta_access_request)
      end

      it "re-renders the 'edit' template" do
        beta_access_request = BetaAccessRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BetaAccessRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => beta_access_request.to_param, :beta_access_request => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested beta_access_request" do
      beta_access_request = BetaAccessRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => beta_access_request.to_param}, valid_session
      }.to change(BetaAccessRequest, :count).by(-1)
    end

    it "redirects to the beta_access_requests list" do
      beta_access_request = BetaAccessRequest.create! valid_attributes
      delete :destroy, {:id => beta_access_request.to_param}, valid_session
      response.should redirect_to(beta_access_requests_url)
    end
  end

end
